# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lcls.ui'
#
# Created: Tue Jul 14 12:38:42 2015
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_pyLCLS(object):
    def setupUi(self, pyLCLS):
        pyLCLS.setObjectName(_fromUtf8("pyLCLS"))
        pyLCLS.resize(1847, 934)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(pyLCLS.sizePolicy().hasHeightForWidth())
        pyLCLS.setSizePolicy(sizePolicy)
        pyLCLS.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/programicons/P11Logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        pyLCLS.setWindowIcon(icon)
        pyLCLS.setAutoFillBackground(False)
        self.centralwidget = QtGui.QWidget(pyLCLS)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 891, 881))
        self.tabWidget.setMouseTracking(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.graphicsviewLiveview = QtGui.QGraphicsView(self.tab)
        self.graphicsviewLiveview.setGeometry(QtCore.QRect(20, 10, 851, 638))
        self.graphicsviewLiveview.setSizeIncrement(QtCore.QSize(1, 1))
        self.graphicsviewLiveview.setMouseTracking(True)
        self.graphicsviewLiveview.setLineWidth(0)
        self.graphicsviewLiveview.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsviewLiveview.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsviewLiveview.setObjectName(_fromUtf8("graphicsviewLiveview"))
        self.label_14 = QtGui.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(25, 660, 81, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.spinboxGain = QtGui.QSpinBox(self.tab)
        self.spinboxGain.setGeometry(QtCore.QRect(140, 660, 131, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinboxGain.setFont(font)
        self.spinboxGain.setMaximum(999999999)
        self.spinboxGain.setObjectName(_fromUtf8("spinboxGain"))
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(25, 690, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.spinboxExposureTime = QtGui.QSpinBox(self.tab)
        self.spinboxExposureTime.setGeometry(QtCore.QRect(140, 690, 131, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinboxExposureTime.setFont(font)
        self.spinboxExposureTime.setMinimum(1)
        self.spinboxExposureTime.setMaximum(999999999)
        self.spinboxExposureTime.setObjectName(_fromUtf8("spinboxExposureTime"))
        self.label_21 = QtGui.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(25, 720, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setText(_fromUtf8("Scale"))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.doubleSpinBoxPixelsPerUm = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBoxPixelsPerUm.setGeometry(QtCore.QRect(140, 720, 131, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxPixelsPerUm.setFont(font)
        self.doubleSpinBoxPixelsPerUm.setReadOnly(False)
        self.doubleSpinBoxPixelsPerUm.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.doubleSpinBoxPixelsPerUm.setDecimals(4)
        self.doubleSpinBoxPixelsPerUm.setMaximum(1000000000.0)
        self.doubleSpinBoxPixelsPerUm.setSingleStep(0.001)
        self.doubleSpinBoxPixelsPerUm.setProperty("value", 1.0)
        self.doubleSpinBoxPixelsPerUm.setObjectName(_fromUtf8("doubleSpinBoxPixelsPerUm"))
        self.label_40 = QtGui.QLabel(self.tab)
        self.label_40.setGeometry(QtCore.QRect(420, 690, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setText(_fromUtf8("Grid angle"))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.label_41 = QtGui.QLabel(self.tab)
        self.label_41.setGeometry(QtCore.QRect(420, 660, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setText(_fromUtf8("Hole pitch"))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.doubleSpinBoxHolePitch = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBoxHolePitch.setGeometry(QtCore.QRect(510, 660, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxHolePitch.setFont(font)
        self.doubleSpinBoxHolePitch.setDecimals(3)
        self.doubleSpinBoxHolePitch.setMinimum(5.0)
        self.doubleSpinBoxHolePitch.setMaximum(25.0)
        self.doubleSpinBoxHolePitch.setSingleStep(0.001)
        self.doubleSpinBoxHolePitch.setProperty("value", 10.0)
        self.doubleSpinBoxHolePitch.setObjectName(_fromUtf8("doubleSpinBoxHolePitch"))
        self.doubleSpinBoxAngle = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBoxAngle.setGeometry(QtCore.QRect(510, 690, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxAngle.setFont(font)
        self.doubleSpinBoxAngle.setDecimals(3)
        self.doubleSpinBoxAngle.setMinimum(-89.9)
        self.doubleSpinBoxAngle.setMaximum(89.9)
        self.doubleSpinBoxAngle.setSingleStep(0.01)
        self.doubleSpinBoxAngle.setProperty("value", 0.0)
        self.doubleSpinBoxAngle.setObjectName(_fromUtf8("doubleSpinBoxAngle"))
        self.labelNewRoi_5 = QtGui.QLabel(self.tab)
        self.labelNewRoi_5.setGeometry(QtCore.QRect(420, 750, 113, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelNewRoi_5.setFont(font)
        self.labelNewRoi_5.setObjectName(_fromUtf8("labelNewRoi_5"))
        self.doubleSpinBoxBeamsize = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBoxBeamsize.setGeometry(QtCore.QRect(510, 750, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxBeamsize.setFont(font)
        self.doubleSpinBoxBeamsize.setDecimals(1)
        self.doubleSpinBoxBeamsize.setMaximum(999999999.0)
        self.doubleSpinBoxBeamsize.setSingleStep(0.1)
        self.doubleSpinBoxBeamsize.setObjectName(_fromUtf8("doubleSpinBoxBeamsize"))
        self.labelNewRoi_6 = QtGui.QLabel(self.tab)
        self.labelNewRoi_6.setGeometry(QtCore.QRect(420, 780, 113, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelNewRoi_6.setFont(font)
        self.labelNewRoi_6.setObjectName(_fromUtf8("labelNewRoi_6"))
        self.labelNewRoi_7 = QtGui.QLabel(self.tab)
        self.labelNewRoi_7.setGeometry(QtCore.QRect(420, 810, 113, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelNewRoi_7.setFont(font)
        self.labelNewRoi_7.setObjectName(_fromUtf8("labelNewRoi_7"))
        self.spinBoxBeamX = QtGui.QSpinBox(self.tab)
        self.spinBoxBeamX.setGeometry(QtCore.QRect(510, 780, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBoxBeamX.setFont(font)
        self.spinBoxBeamX.setPrefix(_fromUtf8(""))
        self.spinBoxBeamX.setMinimum(-5000)
        self.spinBoxBeamX.setMaximum(5000)
        self.spinBoxBeamX.setObjectName(_fromUtf8("spinBoxBeamX"))
        self.spinBoxBeamY = QtGui.QSpinBox(self.tab)
        self.spinBoxBeamY.setGeometry(QtCore.QRect(510, 810, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBoxBeamY.setFont(font)
        self.spinBoxBeamY.setPrefix(_fromUtf8(""))
        self.spinBoxBeamY.setMinimum(-5000)
        self.spinBoxBeamY.setMaximum(5000)
        self.spinBoxBeamY.setObjectName(_fromUtf8("spinBoxBeamY"))
        self.pushButtonSetMountPosition = QtGui.QPushButton(self.tab)
        self.pushButtonSetMountPosition.setGeometry(QtCore.QRect(710, 660, 161, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonSetMountPosition.setFont(font)
        self.pushButtonSetMountPosition.setObjectName(_fromUtf8("pushButtonSetMountPosition"))
        self.pushButtonSetBeamPosition = QtGui.QPushButton(self.tab)
        self.pushButtonSetBeamPosition.setGeometry(QtCore.QRect(710, 700, 161, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonSetBeamPosition.setFont(font)
        self.pushButtonSetBeamPosition.setObjectName(_fromUtf8("pushButtonSetBeamPosition"))
        self.doubleSpinBoxYZpitch = QtGui.QDoubleSpinBox(self.tab)
        self.doubleSpinBoxYZpitch.setGeometry(QtCore.QRect(510, 720, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxYZpitch.setFont(font)
        self.doubleSpinBoxYZpitch.setDecimals(3)
        self.doubleSpinBoxYZpitch.setMinimum(-30.0)
        self.doubleSpinBoxYZpitch.setMaximum(30.0)
        self.doubleSpinBoxYZpitch.setSingleStep(0.01)
        self.doubleSpinBoxYZpitch.setProperty("value", 0.0)
        self.doubleSpinBoxYZpitch.setObjectName(_fromUtf8("doubleSpinBoxYZpitch"))
        self.label_42 = QtGui.QLabel(self.tab)
        self.label_42.setGeometry(QtCore.QRect(420, 720, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setText(_fromUtf8("YZ Pitch"))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.pushButtonAutofocusGonioZ = QtGui.QPushButton(self.tab)
        self.pushButtonAutofocusGonioZ.setGeometry(QtCore.QRect(730, 780, 141, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonAutofocusGonioZ.setFont(font)
        self.pushButtonAutofocusGonioZ.setObjectName(_fromUtf8("pushButtonAutofocusGonioZ"))
        self.checkBoxAutoGain = QtGui.QCheckBox(self.tab)
        self.checkBoxAutoGain.setGeometry(QtCore.QRect(280, 660, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxAutoGain.setFont(font)
        self.checkBoxAutoGain.setObjectName(_fromUtf8("checkBoxAutoGain"))
        self.checkBoxAutoExposure = QtGui.QCheckBox(self.tab)
        self.checkBoxAutoExposure.setGeometry(QtCore.QRect(280, 690, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxAutoExposure.setFont(font)
        self.checkBoxAutoExposure.setObjectName(_fromUtf8("checkBoxAutoExposure"))
        self.pushButtonSaveImage = QtGui.QPushButton(self.tab)
        self.pushButtonSaveImage.setGeometry(QtCore.QRect(20, 800, 102, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonSaveImage.setFont(font)
        self.pushButtonSaveImage.setObjectName(_fromUtf8("pushButtonSaveImage"))
        self.pushButtonAutofocusGonio = QtGui.QPushButton(self.tab)
        self.pushButtonAutofocusGonio.setGeometry(QtCore.QRect(730, 810, 141, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonAutofocusGonio.setFont(font)
        self.pushButtonAutofocusGonio.setObjectName(_fromUtf8("pushButtonAutofocusGonio"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.groupBoxGrid = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxGrid.setGeometry(QtCore.QRect(910, 340, 611, 261))
        self.groupBoxGrid.setAutoFillBackground(True)
        self.groupBoxGrid.setFlat(False)
        self.groupBoxGrid.setObjectName(_fromUtf8("groupBoxGrid"))
        self.label_2 = QtGui.QLabel(self.groupBoxGrid)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButtonSetTopLeft = QtGui.QPushButton(self.groupBoxGrid)
        self.pushButtonSetTopLeft.setGeometry(QtCore.QRect(370, 40, 171, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonSetTopLeft.setFont(font)
        self.pushButtonSetTopLeft.setObjectName(_fromUtf8("pushButtonSetTopLeft"))
        self.pushButtonClearRaster = QtGui.QPushButton(self.groupBoxGrid)
        self.pushButtonClearRaster.setGeometry(QtCore.QRect(490, 160, 106, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonClearRaster.setFont(font)
        self.pushButtonClearRaster.setObjectName(_fromUtf8("pushButtonClearRaster"))
        self.doubleSpinBoxTopLeftX = QtGui.QDoubleSpinBox(self.groupBoxGrid)
        self.doubleSpinBoxTopLeftX.setGeometry(QtCore.QRect(180, 40, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxTopLeftX.setFont(font)
        self.doubleSpinBoxTopLeftX.setReadOnly(True)
        self.doubleSpinBoxTopLeftX.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBoxTopLeftX.setMinimum(-10000000.0)
        self.doubleSpinBoxTopLeftX.setMaximum(10000000.0)
        self.doubleSpinBoxTopLeftX.setObjectName(_fromUtf8("doubleSpinBoxTopLeftX"))
        self.doubleSpinBoxTopLeftY = QtGui.QDoubleSpinBox(self.groupBoxGrid)
        self.doubleSpinBoxTopLeftY.setGeometry(QtCore.QRect(270, 40, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxTopLeftY.setFont(font)
        self.doubleSpinBoxTopLeftY.setReadOnly(True)
        self.doubleSpinBoxTopLeftY.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBoxTopLeftY.setMinimum(-10000000.0)
        self.doubleSpinBoxTopLeftY.setMaximum(10000000.0)
        self.doubleSpinBoxTopLeftY.setObjectName(_fromUtf8("doubleSpinBoxTopLeftY"))
        self.checkBoxTopLeftCorner = QtGui.QCheckBox(self.groupBoxGrid)
        self.checkBoxTopLeftCorner.setGeometry(QtCore.QRect(550, 40, 85, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxTopLeftCorner.setFont(font)
        self.checkBoxTopLeftCorner.setCheckable(False)
        self.checkBoxTopLeftCorner.setObjectName(_fromUtf8("checkBoxTopLeftCorner"))
        self.pushButtonSetTopRight = QtGui.QPushButton(self.groupBoxGrid)
        self.pushButtonSetTopRight.setGeometry(QtCore.QRect(370, 100, 171, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonSetTopRight.setFont(font)
        self.pushButtonSetTopRight.setObjectName(_fromUtf8("pushButtonSetTopRight"))
        self.checkBoxTopRightCorner = QtGui.QCheckBox(self.groupBoxGrid)
        self.checkBoxTopRightCorner.setGeometry(QtCore.QRect(550, 100, 85, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxTopRightCorner.setFont(font)
        self.checkBoxTopRightCorner.setCheckable(False)
        self.checkBoxTopRightCorner.setObjectName(_fromUtf8("checkBoxTopRightCorner"))
        self.doubleSpinBoxTopRightX = QtGui.QDoubleSpinBox(self.groupBoxGrid)
        self.doubleSpinBoxTopRightX.setGeometry(QtCore.QRect(180, 100, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxTopRightX.setFont(font)
        self.doubleSpinBoxTopRightX.setReadOnly(True)
        self.doubleSpinBoxTopRightX.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBoxTopRightX.setMinimum(-10000000.0)
        self.doubleSpinBoxTopRightX.setMaximum(10000000.0)
        self.doubleSpinBoxTopRightX.setObjectName(_fromUtf8("doubleSpinBoxTopRightX"))
        self.doubleSpinBoxTopRightY = QtGui.QDoubleSpinBox(self.groupBoxGrid)
        self.doubleSpinBoxTopRightY.setGeometry(QtCore.QRect(270, 100, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxTopRightY.setFont(font)
        self.doubleSpinBoxTopRightY.setReadOnly(True)
        self.doubleSpinBoxTopRightY.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBoxTopRightY.setMinimum(-10000000.0)
        self.doubleSpinBoxTopRightY.setMaximum(10000000.0)
        self.doubleSpinBoxTopRightY.setObjectName(_fromUtf8("doubleSpinBoxTopRightY"))
        self.label_3 = QtGui.QLabel(self.groupBoxGrid)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.pushButtonSetBottomLeft = QtGui.QPushButton(self.groupBoxGrid)
        self.pushButtonSetBottomLeft.setGeometry(QtCore.QRect(370, 130, 171, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonSetBottomLeft.setFont(font)
        self.pushButtonSetBottomLeft.setObjectName(_fromUtf8("pushButtonSetBottomLeft"))
        self.label_4 = QtGui.QLabel(self.groupBoxGrid)
        self.label_4.setGeometry(QtCore.QRect(20, 130, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.doubleSpinBoxBottomLeftY = QtGui.QDoubleSpinBox(self.groupBoxGrid)
        self.doubleSpinBoxBottomLeftY.setGeometry(QtCore.QRect(270, 130, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxBottomLeftY.setFont(font)
        self.doubleSpinBoxBottomLeftY.setReadOnly(True)
        self.doubleSpinBoxBottomLeftY.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBoxBottomLeftY.setMinimum(-10000000.0)
        self.doubleSpinBoxBottomLeftY.setMaximum(10000000.0)
        self.doubleSpinBoxBottomLeftY.setObjectName(_fromUtf8("doubleSpinBoxBottomLeftY"))
        self.doubleSpinBoxBottomLeftX = QtGui.QDoubleSpinBox(self.groupBoxGrid)
        self.doubleSpinBoxBottomLeftX.setGeometry(QtCore.QRect(180, 130, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxBottomLeftX.setFont(font)
        self.doubleSpinBoxBottomLeftX.setReadOnly(True)
        self.doubleSpinBoxBottomLeftX.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.doubleSpinBoxBottomLeftX.setMinimum(-10000000.0)
        self.doubleSpinBoxBottomLeftX.setMaximum(10000000.0)
        self.doubleSpinBoxBottomLeftX.setObjectName(_fromUtf8("doubleSpinBoxBottomLeftX"))
        self.checkBoxBottomLeftCorner = QtGui.QCheckBox(self.groupBoxGrid)
        self.checkBoxBottomLeftCorner.setGeometry(QtCore.QRect(550, 130, 85, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxBottomLeftCorner.setFont(font)
        self.checkBoxBottomLeftCorner.setCheckable(False)
        self.checkBoxBottomLeftCorner.setObjectName(_fromUtf8("checkBoxBottomLeftCorner"))
        self.label_5 = QtGui.QLabel(self.groupBoxGrid)
        self.label_5.setGeometry(QtCore.QRect(180, 20, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBoxGrid)
        self.label_6.setGeometry(QtCore.QRect(270, 20, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBoxGrid)
        self.label_7.setGeometry(QtCore.QRect(20, 70, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.checkBoxAssistline = QtGui.QCheckBox(self.groupBoxGrid)
        self.checkBoxAssistline.setGeometry(QtCore.QRect(180, 70, 85, 21))
        self.checkBoxAssistline.setText(_fromUtf8(""))
        self.checkBoxAssistline.setObjectName(_fromUtf8("checkBoxAssistline"))
        self.doubleSpinBoxAssistlineAngle = QtGui.QDoubleSpinBox(self.groupBoxGrid)
        self.doubleSpinBoxAssistlineAngle.setGeometry(QtCore.QRect(270, 70, 81, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxAssistlineAngle.setFont(font)
        self.doubleSpinBoxAssistlineAngle.setDecimals(3)
        self.doubleSpinBoxAssistlineAngle.setMinimum(-3600.0)
        self.doubleSpinBoxAssistlineAngle.setMaximum(3600.0)
        self.doubleSpinBoxAssistlineAngle.setSingleStep(0.001)
        self.doubleSpinBoxAssistlineAngle.setProperty("value", 0.0)
        self.doubleSpinBoxAssistlineAngle.setObjectName(_fromUtf8("doubleSpinBoxAssistlineAngle"))
        self.label_8 = QtGui.QLabel(self.groupBoxGrid)
        self.label_8.setGeometry(QtCore.QRect(220, 70, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_10 = QtGui.QLabel(self.groupBoxGrid)
        self.label_10.setGeometry(QtCore.QRect(370, 70, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.doubleSpinBoxAssistlineLength = QtGui.QDoubleSpinBox(self.groupBoxGrid)
        self.doubleSpinBoxAssistlineLength.setGeometry(QtCore.QRect(440, 70, 131, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxAssistlineLength.setFont(font)
        self.doubleSpinBoxAssistlineLength.setDecimals(3)
        self.doubleSpinBoxAssistlineLength.setMinimum(1.0)
        self.doubleSpinBoxAssistlineLength.setMaximum(100000000.0)
        self.doubleSpinBoxAssistlineLength.setSingleStep(50.0)
        self.doubleSpinBoxAssistlineLength.setProperty("value", 200.0)
        self.doubleSpinBoxAssistlineLength.setObjectName(_fromUtf8("doubleSpinBoxAssistlineLength"))
        self.label_11 = QtGui.QLabel(self.groupBoxGrid)
        self.label_11.setGeometry(QtCore.QRect(20, 150, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.checkBoxOrtholines = QtGui.QCheckBox(self.groupBoxGrid)
        self.checkBoxOrtholines.setGeometry(QtCore.QRect(180, 160, 85, 21))
        self.checkBoxOrtholines.setText(_fromUtf8(""))
        self.checkBoxOrtholines.setChecked(True)
        self.checkBoxOrtholines.setObjectName(_fromUtf8("checkBoxOrtholines"))
        self.label_16 = QtGui.QLabel(self.groupBoxGrid)
        self.label_16.setGeometry(QtCore.QRect(20, 200, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.groupBoxGrid)
        self.label_17.setGeometry(QtCore.QRect(170, 190, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.spinBoxGotoHoleNumber = QtGui.QSpinBox(self.groupBoxGrid)
        self.spinBoxGotoHoleNumber.setGeometry(QtCore.QRect(220, 200, 51, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBoxGotoHoleNumber.setFont(font)
        self.spinBoxGotoHoleNumber.setMinimum(1)
        self.spinBoxGotoHoleNumber.setMaximum(300)
        self.spinBoxGotoHoleNumber.setObjectName(_fromUtf8("spinBoxGotoHoleNumber"))
        self.pushButtonGoRowHole = QtGui.QPushButton(self.groupBoxGrid)
        self.pushButtonGoRowHole.setGeometry(QtCore.QRect(280, 200, 41, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonGoRowHole.setFont(font)
        self.pushButtonGoRowHole.setObjectName(_fromUtf8("pushButtonGoRowHole"))
        self.spinBoxGotoRowNumber = QtGui.QSpinBox(self.groupBoxGrid)
        self.spinBoxGotoRowNumber.setGeometry(QtCore.QRect(100, 200, 61, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBoxGotoRowNumber.setFont(font)
        self.spinBoxGotoRowNumber.setMinimum(1)
        self.spinBoxGotoRowNumber.setMaximum(300)
        self.spinBoxGotoRowNumber.setObjectName(_fromUtf8("spinBoxGotoRowNumber"))
        self.label_28 = QtGui.QLabel(self.groupBoxGrid)
        self.label_28.setGeometry(QtCore.QRect(430, 230, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.spinBoxGridWidth = QtGui.QSpinBox(self.groupBoxGrid)
        self.spinBoxGridWidth.setGeometry(QtCore.QRect(515, 230, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBoxGridWidth.setFont(font)
        self.spinBoxGridWidth.setReadOnly(True)
        self.spinBoxGridWidth.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBoxGridWidth.setPrefix(_fromUtf8(""))
        self.spinBoxGridWidth.setMaximum(500)
        self.spinBoxGridWidth.setProperty("value", 0)
        self.spinBoxGridWidth.setObjectName(_fromUtf8("spinBoxGridWidth"))
        self.spinBoxGridHeight = QtGui.QSpinBox(self.groupBoxGrid)
        self.spinBoxGridHeight.setGeometry(QtCore.QRect(515, 200, 81, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBoxGridHeight.setFont(font)
        self.spinBoxGridHeight.setReadOnly(True)
        self.spinBoxGridHeight.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBoxGridHeight.setPrefix(_fromUtf8(""))
        self.spinBoxGridHeight.setMaximum(500)
        self.spinBoxGridHeight.setProperty("value", 0)
        self.spinBoxGridHeight.setObjectName(_fromUtf8("spinBoxGridHeight"))
        self.label_29 = QtGui.QLabel(self.groupBoxGrid)
        self.label_29.setGeometry(QtCore.QRect(430, 200, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.groupBoxScanParameters = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxScanParameters.setGeometry(QtCore.QRect(910, 600, 631, 301))
        self.groupBoxScanParameters.setAutoFillBackground(True)
        self.groupBoxScanParameters.setObjectName(_fromUtf8("groupBoxScanParameters"))
        self.spinBoxCurrentRow = QtGui.QSpinBox(self.groupBoxScanParameters)
        self.spinBoxCurrentRow.setEnabled(True)
        self.spinBoxCurrentRow.setGeometry(QtCore.QRect(550, 130, 51, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBoxCurrentRow.setFont(font)
        self.spinBoxCurrentRow.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBoxCurrentRow.setMaximum(100000000)
        self.spinBoxCurrentRow.setObjectName(_fromUtf8("spinBoxCurrentRow"))
        self.pushButtonStartScan = QtGui.QPushButton(self.groupBoxScanParameters)
        self.pushButtonStartScan.setGeometry(QtCore.QRect(10, 240, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonStartScan.setFont(font)
        self.pushButtonStartScan.setObjectName(_fromUtf8("pushButtonStartScan"))
        self.label_13 = QtGui.QLabel(self.groupBoxScanParameters)
        self.label_13.setGeometry(QtCore.QRect(10, 30, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_144 = QtGui.QLabel(self.groupBoxScanParameters)
        self.label_144.setGeometry(QtCore.QRect(450, 130, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_144.setFont(font)
        self.label_144.setObjectName(_fromUtf8("label_144"))
        self.lineEditScanName = QtGui.QLineEdit(self.groupBoxScanParameters)
        self.lineEditScanName.setGeometry(QtCore.QRect(130, 40, 241, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditScanName.setFont(font)
        self.lineEditScanName.setObjectName(_fromUtf8("lineEditScanName"))
        self.label_15 = QtGui.QLabel(self.groupBoxScanParameters)
        self.label_15.setGeometry(QtCore.QRect(10, 60, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.doubleSpinBoxStartAngleInc = QtGui.QDoubleSpinBox(self.groupBoxScanParameters)
        self.doubleSpinBoxStartAngleInc.setGeometry(QtCore.QRect(130, 70, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxStartAngleInc.setFont(font)
        self.doubleSpinBoxStartAngleInc.setDecimals(3)
        self.doubleSpinBoxStartAngleInc.setMinimum(-3600.0)
        self.doubleSpinBoxStartAngleInc.setMaximum(3600.0)
        self.doubleSpinBoxStartAngleInc.setSingleStep(0.001)
        self.doubleSpinBoxStartAngleInc.setProperty("value", 0.0)
        self.doubleSpinBoxStartAngleInc.setObjectName(_fromUtf8("doubleSpinBoxStartAngleInc"))
        self.label_18 = QtGui.QLabel(self.groupBoxScanParameters)
        self.label_18.setGeometry(QtCore.QRect(10, 130, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.spinBoxScanStartRow = QtGui.QSpinBox(self.groupBoxScanParameters)
        self.spinBoxScanStartRow.setGeometry(QtCore.QRect(130, 130, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBoxScanStartRow.setFont(font)
        self.spinBoxScanStartRow.setMaximum(300)
        self.spinBoxScanStartRow.setObjectName(_fromUtf8("spinBoxScanStartRow"))
        self.label_19 = QtGui.QLabel(self.groupBoxScanParameters)
        self.label_19.setGeometry(QtCore.QRect(260, 130, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.spinBoxScanStopRow = QtGui.QSpinBox(self.groupBoxScanParameters)
        self.spinBoxScanStopRow.setGeometry(QtCore.QRect(240, 130, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBoxScanStopRow.setFont(font)
        self.spinBoxScanStopRow.setMaximum(300)
        self.spinBoxScanStopRow.setObjectName(_fromUtf8("spinBoxScanStopRow"))
        self.label_20 = QtGui.QLabel(self.groupBoxScanParameters)
        self.label_20.setGeometry(QtCore.QRect(450, 10, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.spinBoxGlobalRunNumber = QtGui.QSpinBox(self.groupBoxScanParameters)
        self.spinBoxGlobalRunNumber.setGeometry(QtCore.QRect(450, 40, 71, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBoxGlobalRunNumber.setFont(font)
        self.spinBoxGlobalRunNumber.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.spinBoxGlobalRunNumber.setMaximum(10000000)
        self.spinBoxGlobalRunNumber.setObjectName(_fromUtf8("spinBoxGlobalRunNumber"))
        self.progressBarScanStatus = QtGui.QProgressBar(self.groupBoxScanParameters)
        self.progressBarScanStatus.setGeometry(QtCore.QRect(10, 280, 621, 21))
        self.progressBarScanStatus.setProperty("value", 0)
        self.progressBarScanStatus.setObjectName(_fromUtf8("progressBarScanStatus"))
        self.pushButtonAbortScan = QtGui.QPushButton(self.groupBoxScanParameters)
        self.pushButtonAbortScan.setGeometry(QtCore.QRect(530, 240, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonAbortScan.setFont(font)
        self.pushButtonAbortScan.setObjectName(_fromUtf8("pushButtonAbortScan"))
        self.label_22 = QtGui.QLabel(self.groupBoxScanParameters)
        self.label_22.setGeometry(QtCore.QRect(10, 90, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.doubleSpinBoxEndAngleInc = QtGui.QDoubleSpinBox(self.groupBoxScanParameters)
        self.doubleSpinBoxEndAngleInc.setGeometry(QtCore.QRect(130, 100, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxEndAngleInc.setFont(font)
        self.doubleSpinBoxEndAngleInc.setDecimals(3)
        self.doubleSpinBoxEndAngleInc.setMinimum(-3600.0)
        self.doubleSpinBoxEndAngleInc.setMaximum(3600.0)
        self.doubleSpinBoxEndAngleInc.setSingleStep(0.001)
        self.doubleSpinBoxEndAngleInc.setProperty("value", 0.0)
        self.doubleSpinBoxEndAngleInc.setObjectName(_fromUtf8("doubleSpinBoxEndAngleInc"))
        self.label_25 = QtGui.QLabel(self.groupBoxScanParameters)
        self.label_25.setGeometry(QtCore.QRect(10, 160, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.spinBoxMachineFrequency = QtGui.QSpinBox(self.groupBoxScanParameters)
        self.spinBoxMachineFrequency.setGeometry(QtCore.QRect(130, 160, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBoxMachineFrequency.setFont(font)
        self.spinBoxMachineFrequency.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.spinBoxMachineFrequency.setReadOnly(False)
        self.spinBoxMachineFrequency.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.spinBoxMachineFrequency.setMinimum(1)
        self.spinBoxMachineFrequency.setMaximum(120)
        self.spinBoxMachineFrequency.setSingleStep(10)
        self.spinBoxMachineFrequency.setProperty("value", 120)
        self.spinBoxMachineFrequency.setObjectName(_fromUtf8("spinBoxMachineFrequency"))
        self.label_26 = QtGui.QLabel(self.groupBoxScanParameters)
        self.label_26.setGeometry(QtCore.QRect(210, 130, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.groupBoxScanParameters)
        self.label_27.setGeometry(QtCore.QRect(210, 160, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.spinBoxAccPulses = QtGui.QSpinBox(self.groupBoxScanParameters)
        self.spinBoxAccPulses.setGeometry(QtCore.QRect(350, 160, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.spinBoxAccPulses.setFont(font)
        self.spinBoxAccPulses.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.spinBoxAccPulses.setReadOnly(False)
        self.spinBoxAccPulses.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.spinBoxAccPulses.setSuffix(_fromUtf8(""))
        self.spinBoxAccPulses.setMaximum(120)
        self.spinBoxAccPulses.setSingleStep(1)
        self.spinBoxAccPulses.setProperty("value", 0)
        self.spinBoxAccPulses.setObjectName(_fromUtf8("spinBoxAccPulses"))
        self.checkBoxScanRunning = QtGui.QCheckBox(self.groupBoxScanParameters)
        self.checkBoxScanRunning.setEnabled(True)
        self.checkBoxScanRunning.setGeometry(QtCore.QRect(530, 170, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxScanRunning.setFont(font)
        self.checkBoxScanRunning.setCheckable(True)
        self.checkBoxScanRunning.setObjectName(_fromUtf8("checkBoxScanRunning"))
        self.tabAlignment = QtGui.QTabWidget(self.centralwidget)
        self.tabAlignment.setGeometry(QtCore.QRect(910, 10, 881, 321))
        self.tabAlignment.setObjectName(_fromUtf8("tabAlignment"))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBoxISMOalignment = QtGui.QGroupBox(self.tab_2)
        self.groupBoxISMOalignment.setGeometry(QtCore.QRect(0, 0, 831, 291))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBoxISMOalignment.setFont(font)
        self.groupBoxISMOalignment.setAutoFillBackground(True)
        self.groupBoxISMOalignment.setTitle(_fromUtf8(""))
        self.groupBoxISMOalignment.setObjectName(_fromUtf8("groupBoxISMOalignment"))
        self.label_140 = QtGui.QLabel(self.groupBoxISMOalignment)
        self.label_140.setGeometry(QtCore.QRect(350, 150, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_140.setFont(font)
        self.label_140.setObjectName(_fromUtf8("label_140"))
        self.pushButtonRight = QtGui.QPushButton(self.groupBoxISMOalignment)
        self.pushButtonRight.setGeometry(QtCore.QRect(100, 80, 41, 41))
        self.pushButtonRight.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButtonRight.setAutoFillBackground(False)
        self.pushButtonRight.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/programicons/arrowRightT.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonRight.setIcon(icon1)
        self.pushButtonRight.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonRight.setObjectName(_fromUtf8("pushButtonRight"))
        self.pushButtonDown = QtGui.QPushButton(self.groupBoxISMOalignment)
        self.pushButtonDown.setGeometry(QtCore.QRect(60, 120, 41, 41))
        self.pushButtonDown.setAutoFillBackground(False)
        self.pushButtonDown.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/programicons/arrowDownT.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonDown.setIcon(icon2)
        self.pushButtonDown.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonDown.setObjectName(_fromUtf8("pushButtonDown"))
        self.pushButtonResetMotors = QtGui.QPushButton(self.groupBoxISMOalignment)
        self.pushButtonResetMotors.setGeometry(QtCore.QRect(60, 80, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButtonResetMotors.setFont(font)
        self.pushButtonResetMotors.setAutoFillBackground(False)
        self.pushButtonResetMotors.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonResetMotors.setObjectName(_fromUtf8("pushButtonResetMotors"))
        self.doubleSpinBoxScanYposition = QtGui.QDoubleSpinBox(self.groupBoxISMOalignment)
        self.doubleSpinBoxScanYposition.setGeometry(QtCore.QRect(440, 70, 121, 25))
        self.doubleSpinBoxScanYposition.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBoxScanYposition.setReadOnly(False)
        self.doubleSpinBoxScanYposition.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.doubleSpinBoxScanYposition.setDecimals(1)
        self.doubleSpinBoxScanYposition.setMinimum(-99999999.0)
        self.doubleSpinBoxScanYposition.setMaximum(99999999.0)
        self.doubleSpinBoxScanYposition.setProperty("value", 0.0)
        self.doubleSpinBoxScanYposition.setObjectName(_fromUtf8("doubleSpinBoxScanYposition"))
        self.label_141 = QtGui.QLabel(self.groupBoxISMOalignment)
        self.label_141.setGeometry(QtCore.QRect(220, 30, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_141.setFont(font)
        self.label_141.setObjectName(_fromUtf8("label_141"))
        self.horizontalSliderXPosition = QtGui.QSlider(self.groupBoxISMOalignment)
        self.horizontalSliderXPosition.setGeometry(QtCore.QRect(20, 170, 120, 31))
        self.horizontalSliderXPosition.setMinimum(-1500)
        self.horizontalSliderXPosition.setMaximum(1500)
        self.horizontalSliderXPosition.setProperty("value", 0)
        self.horizontalSliderXPosition.setSliderPosition(0)
        self.horizontalSliderXPosition.setTracking(False)
        self.horizontalSliderXPosition.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderXPosition.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horizontalSliderXPosition.setTickInterval(200)
        self.horizontalSliderXPosition.setObjectName(_fromUtf8("horizontalSliderXPosition"))
        self.comboBoxStepSize = QtGui.QComboBox(self.groupBoxISMOalignment)
        self.comboBoxStepSize.setGeometry(QtCore.QRect(440, 150, 121, 25))
        self.comboBoxStepSize.setObjectName(_fromUtf8("comboBoxStepSize"))
        self.comboBoxStepSize.addItem(_fromUtf8(""))
        self.comboBoxStepSize.addItem(_fromUtf8(""))
        self.comboBoxStepSize.addItem(_fromUtf8(""))
        self.comboBoxStepSize.addItem(_fromUtf8(""))
        self.comboBoxStepSize.addItem(_fromUtf8(""))
        self.comboBoxStepSize.addItem(_fromUtf8(""))
        self.comboBoxStepSize.addItem(_fromUtf8(""))
        self.comboBoxStepSize.addItem(_fromUtf8(""))
        self.doubleSpinBoxScanXposition = QtGui.QDoubleSpinBox(self.groupBoxISMOalignment)
        self.doubleSpinBoxScanXposition.setGeometry(QtCore.QRect(440, 31, 121, 25))
        self.doubleSpinBoxScanXposition.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBoxScanXposition.setReadOnly(False)
        self.doubleSpinBoxScanXposition.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.doubleSpinBoxScanXposition.setDecimals(1)
        self.doubleSpinBoxScanXposition.setMinimum(-99999999.0)
        self.doubleSpinBoxScanXposition.setMaximum(99999999.0)
        self.doubleSpinBoxScanXposition.setProperty("value", 0.0)
        self.doubleSpinBoxScanXposition.setObjectName(_fromUtf8("doubleSpinBoxScanXposition"))
        self.label_142 = QtGui.QLabel(self.groupBoxISMOalignment)
        self.label_142.setGeometry(QtCore.QRect(220, 70, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_142.setFont(font)
        self.label_142.setObjectName(_fromUtf8("label_142"))
        self.pushButtonUp = QtGui.QPushButton(self.groupBoxISMOalignment)
        self.pushButtonUp.setGeometry(QtCore.QRect(60, 40, 41, 41))
        self.pushButtonUp.setAutoFillBackground(False)
        self.pushButtonUp.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/programicons/arrowUpT.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonUp.setIcon(icon3)
        self.pushButtonUp.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonUp.setObjectName(_fromUtf8("pushButtonUp"))
        self.verticalSliderYPosition = QtGui.QSlider(self.groupBoxISMOalignment)
        self.verticalSliderYPosition.setGeometry(QtCore.QRect(165, 40, 31, 120))
        self.verticalSliderYPosition.setMinimum(-1500)
        self.verticalSliderYPosition.setMaximum(1500)
        self.verticalSliderYPosition.setPageStep(10)
        self.verticalSliderYPosition.setProperty("value", 500)
        self.verticalSliderYPosition.setTracking(False)
        self.verticalSliderYPosition.setOrientation(QtCore.Qt.Vertical)
        self.verticalSliderYPosition.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verticalSliderYPosition.setTickInterval(200)
        self.verticalSliderYPosition.setObjectName(_fromUtf8("verticalSliderYPosition"))
        self.pushButtonLeft = QtGui.QPushButton(self.groupBoxISMOalignment)
        self.pushButtonLeft.setGeometry(QtCore.QRect(20, 80, 41, 41))
        self.pushButtonLeft.setAutoFillBackground(False)
        self.pushButtonLeft.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/programicons/arrowLeftT.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonLeft.setIcon(icon4)
        self.pushButtonLeft.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonLeft.setObjectName(_fromUtf8("pushButtonLeft"))
        self.labelScanXposition = QtGui.QLabel(self.groupBoxISMOalignment)
        self.labelScanXposition.setGeometry(QtCore.QRect(310, 30, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelScanXposition.setFont(font)
        self.labelScanXposition.setFrameShape(QtGui.QFrame.Box)
        self.labelScanXposition.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelScanXposition.setObjectName(_fromUtf8("labelScanXposition"))
        self.labelScanYposition = QtGui.QLabel(self.groupBoxISMOalignment)
        self.labelScanYposition.setGeometry(QtCore.QRect(310, 70, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelScanYposition.setFont(font)
        self.labelScanYposition.setFrameShape(QtGui.QFrame.Box)
        self.labelScanYposition.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelScanYposition.setObjectName(_fromUtf8("labelScanYposition"))
        self.pushButtonStopAll = QtGui.QPushButton(self.groupBoxISMOalignment)
        self.pushButtonStopAll.setGeometry(QtCore.QRect(590, 180, 81, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonStopAll.setFont(font)
        self.pushButtonStopAll.setObjectName(_fromUtf8("pushButtonStopAll"))
        self.label_12 = QtGui.QLabel(self.groupBoxISMOalignment)
        self.label_12.setGeometry(QtCore.QRect(210, 190, 151, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.doubleSpinBoxGonioAngle = QtGui.QDoubleSpinBox(self.groupBoxISMOalignment)
        self.doubleSpinBoxGonioAngle.setGeometry(QtCore.QRect(440, 190, 121, 25))
        self.doubleSpinBoxGonioAngle.setDecimals(3)
        self.doubleSpinBoxGonioAngle.setMinimum(-3600.0)
        self.doubleSpinBoxGonioAngle.setMaximum(3600.0)
        self.doubleSpinBoxGonioAngle.setSingleStep(0.1)
        self.doubleSpinBoxGonioAngle.setProperty("value", 0.0)
        self.doubleSpinBoxGonioAngle.setObjectName(_fromUtf8("doubleSpinBoxGonioAngle"))
        self.labelGonioAngle = QtGui.QLabel(self.groupBoxISMOalignment)
        self.labelGonioAngle.setGeometry(QtCore.QRect(310, 190, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelGonioAngle.setFont(font)
        self.labelGonioAngle.setFrameShape(QtGui.QFrame.Box)
        self.labelGonioAngle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelGonioAngle.setObjectName(_fromUtf8("labelGonioAngle"))
        self.label_24 = QtGui.QLabel(self.groupBoxISMOalignment)
        self.label_24.setGeometry(QtCore.QRect(20, 220, 191, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.checkBoxSinCosCorrection = QtGui.QCheckBox(self.groupBoxISMOalignment)
        self.checkBoxSinCosCorrection.setEnabled(False)
        self.checkBoxSinCosCorrection.setGeometry(QtCore.QRect(10, 250, 241, 23))
        self.checkBoxSinCosCorrection.setObjectName(_fromUtf8("checkBoxSinCosCorrection"))
        self.pushButtonSetTopLeftCoarse = QtGui.QPushButton(self.groupBoxISMOalignment)
        self.pushButtonSetTopLeftCoarse.setGeometry(QtCore.QRect(620, 10, 102, 28))
        self.pushButtonSetTopLeftCoarse.setObjectName(_fromUtf8("pushButtonSetTopLeftCoarse"))
        self.pushButtonMoveTopLeft = QtGui.QPushButton(self.groupBoxISMOalignment)
        self.pushButtonMoveTopLeft.setGeometry(QtCore.QRect(610, 40, 41, 41))
        self.pushButtonMoveTopLeft.setAutoFillBackground(False)
        self.pushButtonMoveTopLeft.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/programicons/cornerTopLeft.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonMoveTopLeft.setIcon(icon5)
        self.pushButtonMoveTopLeft.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonMoveTopLeft.setObjectName(_fromUtf8("pushButtonMoveTopLeft"))
        self.pushButtonMoveTopRight = QtGui.QPushButton(self.groupBoxISMOalignment)
        self.pushButtonMoveTopRight.setGeometry(QtCore.QRect(690, 40, 41, 41))
        self.pushButtonMoveTopRight.setAutoFillBackground(False)
        self.pushButtonMoveTopRight.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/programicons/cornerTopRight.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonMoveTopRight.setIcon(icon6)
        self.pushButtonMoveTopRight.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonMoveTopRight.setObjectName(_fromUtf8("pushButtonMoveTopRight"))
        self.pushButtonMoveBottomLeft = QtGui.QPushButton(self.groupBoxISMOalignment)
        self.pushButtonMoveBottomLeft.setGeometry(QtCore.QRect(610, 120, 41, 41))
        self.pushButtonMoveBottomLeft.setAutoFillBackground(False)
        self.pushButtonMoveBottomLeft.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/programicons/cornerBottomLeft.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonMoveBottomLeft.setIcon(icon7)
        self.pushButtonMoveBottomLeft.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonMoveBottomLeft.setObjectName(_fromUtf8("pushButtonMoveBottomLeft"))
        self.pushButtonMoveBottomRight = QtGui.QPushButton(self.groupBoxISMOalignment)
        self.pushButtonMoveBottomRight.setGeometry(QtCore.QRect(690, 120, 41, 41))
        self.pushButtonMoveBottomRight.setAutoFillBackground(False)
        self.pushButtonMoveBottomRight.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/programicons/cornerBottomRight.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonMoveBottomRight.setIcon(icon8)
        self.pushButtonMoveBottomRight.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonMoveBottomRight.setObjectName(_fromUtf8("pushButtonMoveBottomRight"))
        self.pushButtonMoveCentre = QtGui.QPushButton(self.groupBoxISMOalignment)
        self.pushButtonMoveCentre.setGeometry(QtCore.QRect(650, 80, 41, 41))
        self.pushButtonMoveCentre.setAutoFillBackground(False)
        self.pushButtonMoveCentre.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/programicons/cornerCentre.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonMoveCentre.setIcon(icon9)
        self.pushButtonMoveCentre.setIconSize(QtCore.QSize(32, 32))
        self.pushButtonMoveCentre.setObjectName(_fromUtf8("pushButtonMoveCentre"))
        self.label_30 = QtGui.QLabel(self.groupBoxISMOalignment)
        self.label_30.setGeometry(QtCore.QRect(220, 110, 151, 16))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.labelScanZposition = QtGui.QLabel(self.groupBoxISMOalignment)
        self.labelScanZposition.setGeometry(QtCore.QRect(310, 110, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelScanZposition.setFont(font)
        self.labelScanZposition.setFrameShape(QtGui.QFrame.Box)
        self.labelScanZposition.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelScanZposition.setObjectName(_fromUtf8("labelScanZposition"))
        self.doubleSpinBoxScanZposition = QtGui.QDoubleSpinBox(self.groupBoxISMOalignment)
        self.doubleSpinBoxScanZposition.setGeometry(QtCore.QRect(440, 110, 121, 25))
        self.doubleSpinBoxScanZposition.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBoxScanZposition.setReadOnly(False)
        self.doubleSpinBoxScanZposition.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.doubleSpinBoxScanZposition.setDecimals(1)
        self.doubleSpinBoxScanZposition.setMinimum(-99999999.0)
        self.doubleSpinBoxScanZposition.setMaximum(99999999.0)
        self.doubleSpinBoxScanZposition.setProperty("value", 0.0)
        self.doubleSpinBoxScanZposition.setObjectName(_fromUtf8("doubleSpinBoxScanZposition"))
        self.tabAlignment.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.labelOnaxisXposition = QtGui.QLabel(self.tab_3)
        self.labelOnaxisXposition.setGeometry(QtCore.QRect(100, 100, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelOnaxisXposition.setFont(font)
        self.labelOnaxisXposition.setFrameShape(QtGui.QFrame.Box)
        self.labelOnaxisXposition.setTextFormat(QtCore.Qt.PlainText)
        self.labelOnaxisXposition.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelOnaxisXposition.setMargin(0)
        self.labelOnaxisXposition.setIndent(3)
        self.labelOnaxisXposition.setObjectName(_fromUtf8("labelOnaxisXposition"))
        self.doubleSpinBoxOnaxisXposition = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBoxOnaxisXposition.setGeometry(QtCore.QRect(210, 100, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxOnaxisXposition.setFont(font)
        self.doubleSpinBoxOnaxisXposition.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBoxOnaxisXposition.setReadOnly(False)
        self.doubleSpinBoxOnaxisXposition.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.doubleSpinBoxOnaxisXposition.setDecimals(1)
        self.doubleSpinBoxOnaxisXposition.setMinimum(-99999999.0)
        self.doubleSpinBoxOnaxisXposition.setMaximum(99999999.0)
        self.doubleSpinBoxOnaxisXposition.setProperty("value", 0.0)
        self.doubleSpinBoxOnaxisXposition.setObjectName(_fromUtf8("doubleSpinBoxOnaxisXposition"))
        self.label_145 = QtGui.QLabel(self.tab_3)
        self.label_145.setGeometry(QtCore.QRect(10, 100, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_145.setFont(font)
        self.label_145.setObjectName(_fromUtf8("label_145"))
        self.label_146 = QtGui.QLabel(self.tab_3)
        self.label_146.setGeometry(QtCore.QRect(10, 130, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_146.setFont(font)
        self.label_146.setObjectName(_fromUtf8("label_146"))
        self.labelOnaxisYposition = QtGui.QLabel(self.tab_3)
        self.labelOnaxisYposition.setGeometry(QtCore.QRect(100, 130, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelOnaxisYposition.setFont(font)
        self.labelOnaxisYposition.setFrameShape(QtGui.QFrame.Box)
        self.labelOnaxisYposition.setTextFormat(QtCore.Qt.PlainText)
        self.labelOnaxisYposition.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelOnaxisYposition.setMargin(0)
        self.labelOnaxisYposition.setIndent(3)
        self.labelOnaxisYposition.setObjectName(_fromUtf8("labelOnaxisYposition"))
        self.doubleSpinBoxOnaxisYposition = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBoxOnaxisYposition.setGeometry(QtCore.QRect(210, 130, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxOnaxisYposition.setFont(font)
        self.doubleSpinBoxOnaxisYposition.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBoxOnaxisYposition.setReadOnly(False)
        self.doubleSpinBoxOnaxisYposition.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.doubleSpinBoxOnaxisYposition.setDecimals(1)
        self.doubleSpinBoxOnaxisYposition.setMinimum(-99999999.0)
        self.doubleSpinBoxOnaxisYposition.setMaximum(99999999.0)
        self.doubleSpinBoxOnaxisYposition.setProperty("value", 0.0)
        self.doubleSpinBoxOnaxisYposition.setObjectName(_fromUtf8("doubleSpinBoxOnaxisYposition"))
        self.label_147 = QtGui.QLabel(self.tab_3)
        self.label_147.setGeometry(QtCore.QRect(10, 160, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_147.setFont(font)
        self.label_147.setObjectName(_fromUtf8("label_147"))
        self.labelOnaxisZposition = QtGui.QLabel(self.tab_3)
        self.labelOnaxisZposition.setGeometry(QtCore.QRect(100, 160, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelOnaxisZposition.setFont(font)
        self.labelOnaxisZposition.setFrameShape(QtGui.QFrame.Box)
        self.labelOnaxisZposition.setTextFormat(QtCore.Qt.PlainText)
        self.labelOnaxisZposition.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelOnaxisZposition.setMargin(0)
        self.labelOnaxisZposition.setIndent(3)
        self.labelOnaxisZposition.setObjectName(_fromUtf8("labelOnaxisZposition"))
        self.doubleSpinBoxOnaxisZposition = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBoxOnaxisZposition.setGeometry(QtCore.QRect(210, 160, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxOnaxisZposition.setFont(font)
        self.doubleSpinBoxOnaxisZposition.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBoxOnaxisZposition.setReadOnly(False)
        self.doubleSpinBoxOnaxisZposition.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.doubleSpinBoxOnaxisZposition.setDecimals(1)
        self.doubleSpinBoxOnaxisZposition.setMinimum(-99999999.0)
        self.doubleSpinBoxOnaxisZposition.setMaximum(99999999.0)
        self.doubleSpinBoxOnaxisZposition.setProperty("value", 0.0)
        self.doubleSpinBoxOnaxisZposition.setObjectName(_fromUtf8("doubleSpinBoxOnaxisZposition"))
        self.labelBeamstopXposition = QtGui.QLabel(self.tab_3)
        self.labelBeamstopXposition.setGeometry(QtCore.QRect(100, 190, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelBeamstopXposition.setFont(font)
        self.labelBeamstopXposition.setFrameShape(QtGui.QFrame.Box)
        self.labelBeamstopXposition.setTextFormat(QtCore.Qt.PlainText)
        self.labelBeamstopXposition.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelBeamstopXposition.setMargin(0)
        self.labelBeamstopXposition.setIndent(3)
        self.labelBeamstopXposition.setObjectName(_fromUtf8("labelBeamstopXposition"))
        self.label_148 = QtGui.QLabel(self.tab_3)
        self.label_148.setGeometry(QtCore.QRect(10, 190, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_148.setFont(font)
        self.label_148.setObjectName(_fromUtf8("label_148"))
        self.doubleSpinBoxBeamstopXposition = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBoxBeamstopXposition.setGeometry(QtCore.QRect(210, 190, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxBeamstopXposition.setFont(font)
        self.doubleSpinBoxBeamstopXposition.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBoxBeamstopXposition.setReadOnly(False)
        self.doubleSpinBoxBeamstopXposition.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.doubleSpinBoxBeamstopXposition.setDecimals(1)
        self.doubleSpinBoxBeamstopXposition.setMinimum(-99999999.0)
        self.doubleSpinBoxBeamstopXposition.setMaximum(99999999.0)
        self.doubleSpinBoxBeamstopXposition.setProperty("value", 0.0)
        self.doubleSpinBoxBeamstopXposition.setObjectName(_fromUtf8("doubleSpinBoxBeamstopXposition"))
        self.doubleSpinBoxBeamstopYposition = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBoxBeamstopYposition.setGeometry(QtCore.QRect(210, 220, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxBeamstopYposition.setFont(font)
        self.doubleSpinBoxBeamstopYposition.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBoxBeamstopYposition.setReadOnly(False)
        self.doubleSpinBoxBeamstopYposition.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.doubleSpinBoxBeamstopYposition.setDecimals(1)
        self.doubleSpinBoxBeamstopYposition.setMinimum(-99999999.0)
        self.doubleSpinBoxBeamstopYposition.setMaximum(99999999.0)
        self.doubleSpinBoxBeamstopYposition.setProperty("value", 0.0)
        self.doubleSpinBoxBeamstopYposition.setObjectName(_fromUtf8("doubleSpinBoxBeamstopYposition"))
        self.labelBeamstopYposition = QtGui.QLabel(self.tab_3)
        self.labelBeamstopYposition.setGeometry(QtCore.QRect(100, 220, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelBeamstopYposition.setFont(font)
        self.labelBeamstopYposition.setFrameShape(QtGui.QFrame.Box)
        self.labelBeamstopYposition.setTextFormat(QtCore.Qt.PlainText)
        self.labelBeamstopYposition.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelBeamstopYposition.setMargin(0)
        self.labelBeamstopYposition.setIndent(3)
        self.labelBeamstopYposition.setObjectName(_fromUtf8("labelBeamstopYposition"))
        self.label_149 = QtGui.QLabel(self.tab_3)
        self.label_149.setGeometry(QtCore.QRect(10, 220, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_149.setFont(font)
        self.label_149.setObjectName(_fromUtf8("label_149"))
        self.pushButtonStopAll2 = QtGui.QPushButton(self.tab_3)
        self.pushButtonStopAll2.setGeometry(QtCore.QRect(250, 10, 81, 26))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButtonStopAll2.setFont(font)
        self.pushButtonStopAll2.setObjectName(_fromUtf8("pushButtonStopAll2"))
        self.label_23 = QtGui.QLabel(self.tab_3)
        self.label_23.setGeometry(QtCore.QRect(10, 40, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.doubleSpinBoxGonioAngle_2 = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBoxGonioAngle_2.setGeometry(QtCore.QRect(210, 40, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxGonioAngle_2.setFont(font)
        self.doubleSpinBoxGonioAngle_2.setDecimals(3)
        self.doubleSpinBoxGonioAngle_2.setMinimum(-3600.0)
        self.doubleSpinBoxGonioAngle_2.setMaximum(3600.0)
        self.doubleSpinBoxGonioAngle_2.setSingleStep(0.01)
        self.doubleSpinBoxGonioAngle_2.setProperty("value", 0.0)
        self.doubleSpinBoxGonioAngle_2.setObjectName(_fromUtf8("doubleSpinBoxGonioAngle_2"))
        self.labelGonioAngle_2 = QtGui.QLabel(self.tab_3)
        self.labelGonioAngle_2.setGeometry(QtCore.QRect(100, 40, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelGonioAngle_2.setFont(font)
        self.labelGonioAngle_2.setFrameShape(QtGui.QFrame.Box)
        self.labelGonioAngle_2.setTextFormat(QtCore.Qt.PlainText)
        self.labelGonioAngle_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelGonioAngle_2.setMargin(0)
        self.labelGonioAngle_2.setIndent(3)
        self.labelGonioAngle_2.setObjectName(_fromUtf8("labelGonioAngle_2"))
        self.label_150 = QtGui.QLabel(self.tab_3)
        self.label_150.setGeometry(QtCore.QRect(10, 10, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_150.setFont(font)
        self.label_150.setObjectName(_fromUtf8("label_150"))
        self.label_151 = QtGui.QLabel(self.tab_3)
        self.label_151.setGeometry(QtCore.QRect(100, 10, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_151.setFont(font)
        self.label_151.setObjectName(_fromUtf8("label_151"))
        self.label_152 = QtGui.QLabel(self.tab_3)
        self.label_152.setGeometry(QtCore.QRect(210, 10, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_152.setFont(font)
        self.label_152.setObjectName(_fromUtf8("label_152"))
        self.label_153 = QtGui.QLabel(self.tab_3)
        self.label_153.setGeometry(QtCore.QRect(390, 10, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_153.setFont(font)
        self.label_153.setObjectName(_fromUtf8("label_153"))
        self.doubleSpinBoxOnaxisYposition_calib = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBoxOnaxisYposition_calib.setGeometry(QtCore.QRect(380, 130, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxOnaxisYposition_calib.setFont(font)
        self.doubleSpinBoxOnaxisYposition_calib.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBoxOnaxisYposition_calib.setReadOnly(False)
        self.doubleSpinBoxOnaxisYposition_calib.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.doubleSpinBoxOnaxisYposition_calib.setDecimals(1)
        self.doubleSpinBoxOnaxisYposition_calib.setMinimum(-99999999.0)
        self.doubleSpinBoxOnaxisYposition_calib.setMaximum(99999999.0)
        self.doubleSpinBoxOnaxisYposition_calib.setProperty("value", 0.0)
        self.doubleSpinBoxOnaxisYposition_calib.setObjectName(_fromUtf8("doubleSpinBoxOnaxisYposition_calib"))
        self.doubleSpinBoxOnaxisXposition_calib = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBoxOnaxisXposition_calib.setGeometry(QtCore.QRect(380, 100, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxOnaxisXposition_calib.setFont(font)
        self.doubleSpinBoxOnaxisXposition_calib.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBoxOnaxisXposition_calib.setReadOnly(False)
        self.doubleSpinBoxOnaxisXposition_calib.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.doubleSpinBoxOnaxisXposition_calib.setDecimals(1)
        self.doubleSpinBoxOnaxisXposition_calib.setMinimum(-99999999.0)
        self.doubleSpinBoxOnaxisXposition_calib.setMaximum(99999999.0)
        self.doubleSpinBoxOnaxisXposition_calib.setProperty("value", 0.0)
        self.doubleSpinBoxOnaxisXposition_calib.setObjectName(_fromUtf8("doubleSpinBoxOnaxisXposition_calib"))
        self.doubleSpinBoxBeamstopYposition_calib = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBoxBeamstopYposition_calib.setGeometry(QtCore.QRect(380, 220, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxBeamstopYposition_calib.setFont(font)
        self.doubleSpinBoxBeamstopYposition_calib.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBoxBeamstopYposition_calib.setReadOnly(False)
        self.doubleSpinBoxBeamstopYposition_calib.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.doubleSpinBoxBeamstopYposition_calib.setDecimals(1)
        self.doubleSpinBoxBeamstopYposition_calib.setMinimum(-99999999.0)
        self.doubleSpinBoxBeamstopYposition_calib.setMaximum(99999999.0)
        self.doubleSpinBoxBeamstopYposition_calib.setProperty("value", 0.0)
        self.doubleSpinBoxBeamstopYposition_calib.setObjectName(_fromUtf8("doubleSpinBoxBeamstopYposition_calib"))
        self.doubleSpinBoxBeamstopXposition_calib = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBoxBeamstopXposition_calib.setGeometry(QtCore.QRect(380, 190, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxBeamstopXposition_calib.setFont(font)
        self.doubleSpinBoxBeamstopXposition_calib.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBoxBeamstopXposition_calib.setReadOnly(False)
        self.doubleSpinBoxBeamstopXposition_calib.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.doubleSpinBoxBeamstopXposition_calib.setDecimals(1)
        self.doubleSpinBoxBeamstopXposition_calib.setMinimum(-99999999.0)
        self.doubleSpinBoxBeamstopXposition_calib.setMaximum(99999999.0)
        self.doubleSpinBoxBeamstopXposition_calib.setProperty("value", 0.0)
        self.doubleSpinBoxBeamstopXposition_calib.setObjectName(_fromUtf8("doubleSpinBoxBeamstopXposition_calib"))
        self.doubleSpinBoxOnaxisZposition_calib = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBoxOnaxisZposition_calib.setGeometry(QtCore.QRect(380, 160, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxOnaxisZposition_calib.setFont(font)
        self.doubleSpinBoxOnaxisZposition_calib.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBoxOnaxisZposition_calib.setReadOnly(False)
        self.doubleSpinBoxOnaxisZposition_calib.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.doubleSpinBoxOnaxisZposition_calib.setDecimals(1)
        self.doubleSpinBoxOnaxisZposition_calib.setMinimum(-99999999.0)
        self.doubleSpinBoxOnaxisZposition_calib.setMaximum(99999999.0)
        self.doubleSpinBoxOnaxisZposition_calib.setProperty("value", 0.0)
        self.doubleSpinBoxOnaxisZposition_calib.setObjectName(_fromUtf8("doubleSpinBoxOnaxisZposition_calib"))
        self.doubleSpinBoxGonioAngle_calib = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBoxGonioAngle_calib.setGeometry(QtCore.QRect(380, 40, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxGonioAngle_calib.setFont(font)
        self.doubleSpinBoxGonioAngle_calib.setDecimals(3)
        self.doubleSpinBoxGonioAngle_calib.setMinimum(-3600.0)
        self.doubleSpinBoxGonioAngle_calib.setMaximum(3600.0)
        self.doubleSpinBoxGonioAngle_calib.setSingleStep(0.001)
        self.doubleSpinBoxGonioAngle_calib.setProperty("value", 0.0)
        self.doubleSpinBoxGonioAngle_calib.setObjectName(_fromUtf8("doubleSpinBoxGonioAngle_calib"))
        self.label_154 = QtGui.QLabel(self.tab_3)
        self.label_154.setGeometry(QtCore.QRect(10, 250, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_154.setFont(font)
        self.label_154.setObjectName(_fromUtf8("label_154"))
        self.comboBoxStepSize_2 = QtGui.QComboBox(self.tab_3)
        self.comboBoxStepSize_2.setGeometry(QtCore.QRect(210, 250, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBoxStepSize_2.setFont(font)
        self.comboBoxStepSize_2.setObjectName(_fromUtf8("comboBoxStepSize_2"))
        self.comboBoxStepSize_2.addItem(_fromUtf8(""))
        self.comboBoxStepSize_2.addItem(_fromUtf8(""))
        self.comboBoxStepSize_2.addItem(_fromUtf8(""))
        self.comboBoxStepSize_2.addItem(_fromUtf8(""))
        self.comboBoxStepSize_2.addItem(_fromUtf8(""))
        self.comboBoxStepSize_2.addItem(_fromUtf8(""))
        self.comboBoxStepSize_2.addItem(_fromUtf8(""))
        self.comboBoxStepSize_2.addItem(_fromUtf8(""))
        self.doubleSpinBoxGonioZposition = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBoxGonioZposition.setGeometry(QtCore.QRect(210, 70, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxGonioZposition.setFont(font)
        self.doubleSpinBoxGonioZposition.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBoxGonioZposition.setReadOnly(False)
        self.doubleSpinBoxGonioZposition.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.doubleSpinBoxGonioZposition.setDecimals(1)
        self.doubleSpinBoxGonioZposition.setMinimum(-99999999.0)
        self.doubleSpinBoxGonioZposition.setMaximum(99999999.0)
        self.doubleSpinBoxGonioZposition.setProperty("value", 0.0)
        self.doubleSpinBoxGonioZposition.setObjectName(_fromUtf8("doubleSpinBoxGonioZposition"))
        self.labelGonioZposition = QtGui.QLabel(self.tab_3)
        self.labelGonioZposition.setGeometry(QtCore.QRect(100, 70, 101, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelGonioZposition.setFont(font)
        self.labelGonioZposition.setFrameShape(QtGui.QFrame.Box)
        self.labelGonioZposition.setTextFormat(QtCore.Qt.PlainText)
        self.labelGonioZposition.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelGonioZposition.setMargin(0)
        self.labelGonioZposition.setIndent(3)
        self.labelGonioZposition.setObjectName(_fromUtf8("labelGonioZposition"))
        self.label_155 = QtGui.QLabel(self.tab_3)
        self.label_155.setGeometry(QtCore.QRect(10, 70, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_155.setFont(font)
        self.label_155.setObjectName(_fromUtf8("label_155"))
        self.doubleSpinBoxGoniometerZposition_calib = QtGui.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBoxGoniometerZposition_calib.setGeometry(QtCore.QRect(380, 70, 121, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.doubleSpinBoxGoniometerZposition_calib.setFont(font)
        self.doubleSpinBoxGoniometerZposition_calib.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.doubleSpinBoxGoniometerZposition_calib.setReadOnly(False)
        self.doubleSpinBoxGoniometerZposition_calib.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.doubleSpinBoxGoniometerZposition_calib.setDecimals(1)
        self.doubleSpinBoxGoniometerZposition_calib.setMinimum(-99999999.0)
        self.doubleSpinBoxGoniometerZposition_calib.setMaximum(99999999.0)
        self.doubleSpinBoxGoniometerZposition_calib.setProperty("value", 0.0)
        self.doubleSpinBoxGoniometerZposition_calib.setObjectName(_fromUtf8("doubleSpinBoxGoniometerZposition_calib"))
        self.pushButton = QtGui.QPushButton(self.tab_3)
        self.pushButton.setGeometry(QtCore.QRect(730, 10, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.tab_3)
        self.pushButton_2.setGeometry(QtCore.QRect(730, 60, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.tabAlignment.addTab(self.tab_3, _fromUtf8(""))
        pyLCLS.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(pyLCLS)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        pyLCLS.setStatusBar(self.statusbar)

        self.retranslateUi(pyLCLS)
        self.tabWidget.setCurrentIndex(0)
        self.tabAlignment.setCurrentIndex(1)
        self.comboBoxStepSize.setCurrentIndex(0)
        self.comboBoxStepSize_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(pyLCLS)
        pyLCLS.setTabOrder(self.doubleSpinBoxGoniometerZposition_calib, self.doubleSpinBoxOnaxisXposition_calib)
        pyLCLS.setTabOrder(self.doubleSpinBoxOnaxisXposition_calib, self.doubleSpinBoxOnaxisYposition_calib)
        pyLCLS.setTabOrder(self.doubleSpinBoxOnaxisYposition_calib, self.doubleSpinBoxOnaxisZposition_calib)
        pyLCLS.setTabOrder(self.doubleSpinBoxOnaxisZposition_calib, self.doubleSpinBoxBeamstopXposition_calib)
        pyLCLS.setTabOrder(self.doubleSpinBoxBeamstopXposition_calib, self.doubleSpinBoxBeamstopYposition_calib)
        pyLCLS.setTabOrder(self.doubleSpinBoxBeamstopYposition_calib, self.doubleSpinBoxTopLeftX)
        pyLCLS.setTabOrder(self.doubleSpinBoxTopLeftX, self.doubleSpinBoxTopLeftY)
        pyLCLS.setTabOrder(self.doubleSpinBoxTopLeftY, self.doubleSpinBoxAssistlineAngle)
        pyLCLS.setTabOrder(self.doubleSpinBoxAssistlineAngle, self.doubleSpinBoxAssistlineLength)
        pyLCLS.setTabOrder(self.doubleSpinBoxAssistlineLength, self.doubleSpinBoxTopRightX)
        pyLCLS.setTabOrder(self.doubleSpinBoxTopRightX, self.doubleSpinBoxTopRightY)
        pyLCLS.setTabOrder(self.doubleSpinBoxTopRightY, self.doubleSpinBoxBottomLeftX)
        pyLCLS.setTabOrder(self.doubleSpinBoxBottomLeftX, self.doubleSpinBoxBottomLeftY)
        pyLCLS.setTabOrder(self.doubleSpinBoxBottomLeftY, self.spinBoxGotoRowNumber)
        pyLCLS.setTabOrder(self.spinBoxGotoRowNumber, self.spinBoxGotoHoleNumber)
        pyLCLS.setTabOrder(self.spinBoxGotoHoleNumber, self.lineEditScanName)
        pyLCLS.setTabOrder(self.lineEditScanName, self.doubleSpinBoxStartAngleInc)
        pyLCLS.setTabOrder(self.doubleSpinBoxStartAngleInc, self.doubleSpinBoxEndAngleInc)
        pyLCLS.setTabOrder(self.doubleSpinBoxEndAngleInc, self.spinBoxScanStartRow)
        pyLCLS.setTabOrder(self.spinBoxScanStartRow, self.spinBoxScanStopRow)
        pyLCLS.setTabOrder(self.spinBoxScanStopRow, self.doubleSpinBoxScanXposition)
        pyLCLS.setTabOrder(self.doubleSpinBoxScanXposition, self.doubleSpinBoxScanYposition)
        pyLCLS.setTabOrder(self.doubleSpinBoxScanYposition, self.doubleSpinBoxGonioAngle)
        pyLCLS.setTabOrder(self.doubleSpinBoxGonioAngle, self.checkBoxBottomLeftCorner)
        pyLCLS.setTabOrder(self.checkBoxBottomLeftCorner, self.checkBoxAssistline)
        pyLCLS.setTabOrder(self.checkBoxAssistline, self.spinBoxBeamX)
        pyLCLS.setTabOrder(self.spinBoxBeamX, self.spinBoxBeamY)
        pyLCLS.setTabOrder(self.spinBoxBeamY, self.checkBoxOrtholines)
        pyLCLS.setTabOrder(self.checkBoxOrtholines, self.doubleSpinBoxBeamsize)
        pyLCLS.setTabOrder(self.doubleSpinBoxBeamsize, self.pushButtonGoRowHole)
        pyLCLS.setTabOrder(self.pushButtonGoRowHole, self.doubleSpinBoxAngle)
        pyLCLS.setTabOrder(self.doubleSpinBoxAngle, self.spinBoxCurrentRow)
        pyLCLS.setTabOrder(self.spinBoxCurrentRow, self.pushButtonStartScan)
        pyLCLS.setTabOrder(self.pushButtonStartScan, self.checkBoxTopLeftCorner)
        pyLCLS.setTabOrder(self.checkBoxTopLeftCorner, self.pushButtonSetTopRight)
        pyLCLS.setTabOrder(self.pushButtonSetTopRight, self.pushButtonSetMountPosition)
        pyLCLS.setTabOrder(self.pushButtonSetMountPosition, self.pushButtonSetBeamPosition)
        pyLCLS.setTabOrder(self.pushButtonSetBeamPosition, self.spinBoxGlobalRunNumber)
        pyLCLS.setTabOrder(self.spinBoxGlobalRunNumber, self.pushButtonAbortScan)
        pyLCLS.setTabOrder(self.pushButtonAbortScan, self.checkBoxTopRightCorner)
        pyLCLS.setTabOrder(self.checkBoxTopRightCorner, self.tabAlignment)
        pyLCLS.setTabOrder(self.tabAlignment, self.pushButtonRight)
        pyLCLS.setTabOrder(self.pushButtonRight, self.pushButtonDown)
        pyLCLS.setTabOrder(self.pushButtonDown, self.pushButtonResetMotors)
        pyLCLS.setTabOrder(self.pushButtonResetMotors, self.pushButtonClearRaster)
        pyLCLS.setTabOrder(self.pushButtonClearRaster, self.horizontalSliderXPosition)
        pyLCLS.setTabOrder(self.horizontalSliderXPosition, self.comboBoxStepSize)
        pyLCLS.setTabOrder(self.comboBoxStepSize, self.pushButtonSetBottomLeft)
        pyLCLS.setTabOrder(self.pushButtonSetBottomLeft, self.pushButtonUp)
        pyLCLS.setTabOrder(self.pushButtonUp, self.verticalSliderYPosition)
        pyLCLS.setTabOrder(self.verticalSliderYPosition, self.pushButtonLeft)
        pyLCLS.setTabOrder(self.pushButtonLeft, self.pushButtonStopAll)
        pyLCLS.setTabOrder(self.pushButtonStopAll, self.pushButtonSetTopLeft)
        pyLCLS.setTabOrder(self.pushButtonSetTopLeft, self.doubleSpinBoxHolePitch)
        pyLCLS.setTabOrder(self.doubleSpinBoxHolePitch, self.doubleSpinBoxPixelsPerUm)
        pyLCLS.setTabOrder(self.doubleSpinBoxPixelsPerUm, self.spinboxExposureTime)
        pyLCLS.setTabOrder(self.spinboxExposureTime, self.tabWidget)
        pyLCLS.setTabOrder(self.tabWidget, self.graphicsviewLiveview)
        pyLCLS.setTabOrder(self.graphicsviewLiveview, self.pushButtonStopAll2)
        pyLCLS.setTabOrder(self.pushButtonStopAll2, self.spinboxGain)
        pyLCLS.setTabOrder(self.spinboxGain, self.doubleSpinBoxGonioAngle_2)
        pyLCLS.setTabOrder(self.doubleSpinBoxGonioAngle_2, self.doubleSpinBoxGonioZposition)
        pyLCLS.setTabOrder(self.doubleSpinBoxGonioZposition, self.doubleSpinBoxOnaxisXposition)
        pyLCLS.setTabOrder(self.doubleSpinBoxOnaxisXposition, self.doubleSpinBoxOnaxisYposition)
        pyLCLS.setTabOrder(self.doubleSpinBoxOnaxisYposition, self.doubleSpinBoxOnaxisZposition)
        pyLCLS.setTabOrder(self.doubleSpinBoxOnaxisZposition, self.doubleSpinBoxBeamstopXposition)
        pyLCLS.setTabOrder(self.doubleSpinBoxBeamstopXposition, self.doubleSpinBoxBeamstopYposition)
        pyLCLS.setTabOrder(self.doubleSpinBoxBeamstopYposition, self.comboBoxStepSize_2)
        pyLCLS.setTabOrder(self.comboBoxStepSize_2, self.doubleSpinBoxGonioAngle_calib)

    def retranslateUi(self, pyLCLS):
        pyLCLS.setWindowTitle(QtGui.QApplication.translate("pyLCLS", "LCLS Scantool", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("pyLCLS", "Gain", None, QtGui.QApplication.UnicodeUTF8))
        self.spinboxGain.setSuffix(QtGui.QApplication.translate("pyLCLS", " dB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("pyLCLS", "Exposure time", None, QtGui.QApplication.UnicodeUTF8))
        self.spinboxExposureTime.setSuffix(QtGui.QApplication.translate("pyLCLS", " us", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxPixelsPerUm.setSuffix(QtGui.QApplication.translate("pyLCLS", " um/pixel", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxHolePitch.setSuffix(QtGui.QApplication.translate("pyLCLS", " um", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxAngle.setSuffix(QtGui.QApplication.translate("pyLCLS", "°", None, QtGui.QApplication.UnicodeUTF8))
        self.labelNewRoi_5.setText(QtGui.QApplication.translate("pyLCLS", "Beam size", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxBeamsize.setSuffix(QtGui.QApplication.translate("pyLCLS", " um", None, QtGui.QApplication.UnicodeUTF8))
        self.labelNewRoi_6.setText(QtGui.QApplication.translate("pyLCLS", "Beam X", None, QtGui.QApplication.UnicodeUTF8))
        self.labelNewRoi_7.setText(QtGui.QApplication.translate("pyLCLS", "Beam Y", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxBeamX.setSuffix(QtGui.QApplication.translate("pyLCLS", " pix", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxBeamY.setSuffix(QtGui.QApplication.translate("pyLCLS", " pix", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSetMountPosition.setText(QtGui.QApplication.translate("pyLCLS", "Set mount position", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSetBeamPosition.setText(QtGui.QApplication.translate("pyLCLS", "Mark beam position", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxYZpitch.setSuffix(QtGui.QApplication.translate("pyLCLS", "°", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAutofocusGonioZ.setText(QtGui.QApplication.translate("pyLCLS", "Autofocus Gonio Z", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxAutoGain.setText(QtGui.QApplication.translate("pyLCLS", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxAutoExposure.setText(QtGui.QApplication.translate("pyLCLS", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSaveImage.setText(QtGui.QApplication.translate("pyLCLS", "Save image", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAutofocusGonio.setText(QtGui.QApplication.translate("pyLCLS", "Autofocus Gonio", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("pyLCLS", "Live view", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxGrid.setTitle(QtGui.QApplication.translate("pyLCLS", "Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("pyLCLS", "<html><head/><body><p>Top left corner</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSetTopLeft.setText(QtGui.QApplication.translate("pyLCLS", "Set top left corner", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonClearRaster.setText(QtGui.QApplication.translate("pyLCLS", "Clear Raster", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxTopLeftCorner.setText(QtGui.QApplication.translate("pyLCLS", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSetTopRight.setText(QtGui.QApplication.translate("pyLCLS", "Set top right corner", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxTopRightCorner.setText(QtGui.QApplication.translate("pyLCLS", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("pyLCLS", "Top right corner", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSetBottomLeft.setText(QtGui.QApplication.translate("pyLCLS", "Set bottom left corner", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("pyLCLS", "Bottom left corner", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxBottomLeftCorner.setText(QtGui.QApplication.translate("pyLCLS", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("pyLCLS", "Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("pyLCLS", "Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("pyLCLS", "Assist line", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxAssistlineAngle.setSuffix(QtGui.QApplication.translate("pyLCLS", "°", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("pyLCLS", "Angle", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("pyLCLS", "Length", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxAssistlineLength.setSuffix(QtGui.QApplication.translate("pyLCLS", " um", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("pyLCLS", "Corners and\n"
"orthogonal lines", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("pyLCLS", "Go to row", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("pyLCLS", "hole #", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonGoRowHole.setText(QtGui.QApplication.translate("pyLCLS", "Go", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("pyLCLS", "Grid width", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxGridWidth.setSuffix(QtGui.QApplication.translate("pyLCLS", " holes", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxGridHeight.setSuffix(QtGui.QApplication.translate("pyLCLS", " rows", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("pyLCLS", "Grid height", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxScanParameters.setTitle(QtGui.QApplication.translate("pyLCLS", "Scan parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonStartScan.setText(QtGui.QApplication.translate("pyLCLS", "Start scan", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("pyLCLS", "Scan name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_144.setText(QtGui.QApplication.translate("pyLCLS", "Current row", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("pyLCLS", "Gonio start angle", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxStartAngleInc.setSuffix(QtGui.QApplication.translate("pyLCLS", "°", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("pyLCLS", "From row", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("pyLCLS", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("pyLCLS", "Global run number", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAbortScan.setText(QtGui.QApplication.translate("pyLCLS", "Abort scan", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("pyLCLS", "Gonio stop angle", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxEndAngleInc.setSuffix(QtGui.QApplication.translate("pyLCLS", "°", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("pyLCLS", "Pulse frequency", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxMachineFrequency.setSuffix(QtGui.QApplication.translate("pyLCLS", " Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("pyLCLS", "to", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("pyLCLS", "Acceleration pulses", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxScanRunning.setText(QtGui.QApplication.translate("pyLCLS", "Sync script\n"
"running", None, QtGui.QApplication.UnicodeUTF8))
        self.label_140.setText(QtGui.QApplication.translate("pyLCLS", "Step size", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonResetMotors.setText(QtGui.QApplication.translate("pyLCLS", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxScanYposition.setSuffix(QtGui.QApplication.translate("pyLCLS", " μm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_141.setText(QtGui.QApplication.translate("pyLCLS", "X Position", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxStepSize.setItemText(0, QtGui.QApplication.translate("pyLCLS", "1 μm", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxStepSize.setItemText(1, QtGui.QApplication.translate("pyLCLS", "5 μm", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxStepSize.setItemText(2, QtGui.QApplication.translate("pyLCLS", "10 μm", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxStepSize.setItemText(3, QtGui.QApplication.translate("pyLCLS", "50 μm", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxStepSize.setItemText(4, QtGui.QApplication.translate("pyLCLS", "100 μm", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxStepSize.setItemText(5, QtGui.QApplication.translate("pyLCLS", "250 μm", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxStepSize.setItemText(6, QtGui.QApplication.translate("pyLCLS", "500 μm", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxStepSize.setItemText(7, QtGui.QApplication.translate("pyLCLS", "1000 μm", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxScanXposition.setSuffix(QtGui.QApplication.translate("pyLCLS", " μm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_142.setText(QtGui.QApplication.translate("pyLCLS", "Y Position", None, QtGui.QApplication.UnicodeUTF8))
        self.labelScanXposition.setText(QtGui.QApplication.translate("pyLCLS", "0.00 μm", None, QtGui.QApplication.UnicodeUTF8))
        self.labelScanYposition.setText(QtGui.QApplication.translate("pyLCLS", "0.00 μm", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonStopAll.setText(QtGui.QApplication.translate("pyLCLS", "Stop all", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("pyLCLS", "Goniometer", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxGonioAngle.setSuffix(QtGui.QApplication.translate("pyLCLS", "°", None, QtGui.QApplication.UnicodeUTF8))
        self.labelGonioAngle.setText(QtGui.QApplication.translate("pyLCLS", "0.000°", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("pyLCLS", "(right click for move on click)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxSinCosCorrection.setText(QtGui.QApplication.translate("pyLCLS", "Sin/cos goniometer correction", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSetTopLeftCoarse.setText(QtGui.QApplication.translate("pyLCLS", "Set top left", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("pyLCLS", "Z Position", None, QtGui.QApplication.UnicodeUTF8))
        self.labelScanZposition.setText(QtGui.QApplication.translate("pyLCLS", "0.00 μm", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxScanZposition.setSuffix(QtGui.QApplication.translate("pyLCLS", " μm", None, QtGui.QApplication.UnicodeUTF8))
        self.tabAlignment.setTabText(self.tabAlignment.indexOf(self.tab_2), QtGui.QApplication.translate("pyLCLS", "Chip alignment", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOnaxisXposition.setText(QtGui.QApplication.translate("pyLCLS", "0.00 μm", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxOnaxisXposition.setSuffix(QtGui.QApplication.translate("pyLCLS", " μm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_145.setText(QtGui.QApplication.translate("pyLCLS", "Onaxis X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_146.setText(QtGui.QApplication.translate("pyLCLS", "Onaxis Y", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOnaxisYposition.setText(QtGui.QApplication.translate("pyLCLS", "0.00 μm", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxOnaxisYposition.setSuffix(QtGui.QApplication.translate("pyLCLS", " μm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_147.setText(QtGui.QApplication.translate("pyLCLS", "Onaxis Z", None, QtGui.QApplication.UnicodeUTF8))
        self.labelOnaxisZposition.setText(QtGui.QApplication.translate("pyLCLS", "0.00 μm", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxOnaxisZposition.setSuffix(QtGui.QApplication.translate("pyLCLS", " μm", None, QtGui.QApplication.UnicodeUTF8))
        self.labelBeamstopXposition.setText(QtGui.QApplication.translate("pyLCLS", "0.00 μm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_148.setText(QtGui.QApplication.translate("pyLCLS", "Beamstop X", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxBeamstopXposition.setSuffix(QtGui.QApplication.translate("pyLCLS", " μm", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxBeamstopYposition.setSuffix(QtGui.QApplication.translate("pyLCLS", " μm", None, QtGui.QApplication.UnicodeUTF8))
        self.labelBeamstopYposition.setText(QtGui.QApplication.translate("pyLCLS", "0.00 μm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_149.setText(QtGui.QApplication.translate("pyLCLS", "Beamstop Y", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonStopAll2.setText(QtGui.QApplication.translate("pyLCLS", "Stop all", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("pyLCLS", "Goniometer", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxGonioAngle_2.setSuffix(QtGui.QApplication.translate("pyLCLS", "°", None, QtGui.QApplication.UnicodeUTF8))
        self.labelGonioAngle_2.setText(QtGui.QApplication.translate("pyLCLS", "0.00°", None, QtGui.QApplication.UnicodeUTF8))
        self.label_150.setText(QtGui.QApplication.translate("pyLCLS", "Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.label_151.setText(QtGui.QApplication.translate("pyLCLS", "Current ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_152.setText(QtGui.QApplication.translate("pyLCLS", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.label_153.setText(QtGui.QApplication.translate("pyLCLS", "Calibrate position", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxOnaxisYposition_calib.setSuffix(QtGui.QApplication.translate("pyLCLS", " μm", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxOnaxisXposition_calib.setSuffix(QtGui.QApplication.translate("pyLCLS", " μm", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxBeamstopYposition_calib.setSuffix(QtGui.QApplication.translate("pyLCLS", " μm", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxBeamstopXposition_calib.setSuffix(QtGui.QApplication.translate("pyLCLS", " μm", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxOnaxisZposition_calib.setSuffix(QtGui.QApplication.translate("pyLCLS", " μm", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxGonioAngle_calib.setSuffix(QtGui.QApplication.translate("pyLCLS", "°", None, QtGui.QApplication.UnicodeUTF8))
        self.label_154.setText(QtGui.QApplication.translate("pyLCLS", "Step size", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxStepSize_2.setItemText(0, QtGui.QApplication.translate("pyLCLS", "1 μm", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxStepSize_2.setItemText(1, QtGui.QApplication.translate("pyLCLS", "5 μm", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxStepSize_2.setItemText(2, QtGui.QApplication.translate("pyLCLS", "10 μm", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxStepSize_2.setItemText(3, QtGui.QApplication.translate("pyLCLS", "50 μm", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxStepSize_2.setItemText(4, QtGui.QApplication.translate("pyLCLS", "100 μm", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxStepSize_2.setItemText(5, QtGui.QApplication.translate("pyLCLS", "250 μm", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxStepSize_2.setItemText(6, QtGui.QApplication.translate("pyLCLS", "500 μm", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxStepSize_2.setItemText(7, QtGui.QApplication.translate("pyLCLS", "1000 μm", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxGonioZposition.setSuffix(QtGui.QApplication.translate("pyLCLS", " μm", None, QtGui.QApplication.UnicodeUTF8))
        self.labelGonioZposition.setText(QtGui.QApplication.translate("pyLCLS", "0.00 μm", None, QtGui.QApplication.UnicodeUTF8))
        self.label_155.setText(QtGui.QApplication.translate("pyLCLS", "Gonio Z", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBoxGoniometerZposition_calib.setSuffix(QtGui.QApplication.translate("pyLCLS", " μm", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("pyLCLS", "Reset and home\n"
"scanning stage X", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("pyLCLS", "Reset and home\n"
"scanning stage Y", None, QtGui.QApplication.UnicodeUTF8))
        self.tabAlignment.setTabText(self.tabAlignment.indexOf(self.tab_3), QtGui.QApplication.translate("pyLCLS", "Microscope / beamstop alignment", None, QtGui.QApplication.UnicodeUTF8))

import guires_rc
